apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: careerhub
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - list:
        elements:
          - name: prod-careerhub-secret-store
            path: envs/prod/careerhub/secret-store
          - name: prod-careerhub-mongodb
            path: envs/prod/careerhub/mongodb
          # - name: prod-careerhub-services
          #   path: envs/prod/careerhub/services
          # - name: prod-careerhub-web
          #   path: envs/prod/careerhub/web
          # - name: prod-careerhub-batch
          #   path: envs/prod/careerhub/batch
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: careerhub/prod
              operator: In
              values: ["prod-careerhub-secret-store"]
        - matchExpressions:
            - key: careerhub/prod
              operator: In
              values: ["prod-careerhub-mongodb"]
        - matchExpressions:
            - key: careerhub/prod
              operator: In
              values: ["prod-careerhub-services"]
        - matchExpressions:
            - key: careerhub/prod
              operator: In
              values: ["prod-careerhub-web", "prod-careerhub-batch"]
  template:
    metadata:
      name: "{{.name}}"
      labels:
        careerhub/prod: "{{.name}}"
    spec:
      project: careerhub
      source:
        repoURL: git@github.com:jyoliar-careerhub/k8s-config.git
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: prod-careerhub
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 0 # ← 0이면 무제한 재시도
          backoff:
            duration: 5s
            maxDuration: 3m
            factor: 2
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
