apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/mongodb/mongodb-kubernetes/1.6.0/public/mongodb-kubernetes.yaml
  - https://raw.githubusercontent.com/mongodb/mongodb-kubernetes/1.6.0/public/crds.yaml

patches:
  - path: mongodb-operator-patch.yaml
